server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: false  # Set to true in production with HTTPS
        http-only: true
        same-site: lax

spring:
  datasource:
    url: jdbc:h2:mem:flowershop
    driver-class-name: org.h2.Driver
    username: admin
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop  # Use 'update' for production
    show-sql: false  # DISABLE SQL LOGGING IN PRODUCTION
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false  # DISABLE FORMATTED SQL LOGGING
  
  h2:
    console:
      enabled: true  # DISABLE H2 CONSOLE IN PRODUCTION

# Logging configuration
logging:
  level:
    com.bbzbl.flowerbouquet: INFO  # Change from DEBUG to INFO
    org.springframework.security: WARN  # Reduce security logging
    org.hibernate.SQL: WARN  # Disable SQL logging
    org.hibernate.type.descriptor.sql.BasicBinder: WARN  # Disable parameter logging